### ISSUE TITLE
Sun's Texture Dump (Mod integration)

### ISSUE THREAD

**Issue by Sunconure11** [ThexXTURBOXx/Reforged#10]
I am working on a set of textures to integrate fairly common materials into this mod, so that if another mod is using them, they can be used in the crafting of certain items of this mod.

I have created a set of copper items (no saber yet)

I will not do steel, bronze, or less common modded materials. Instead, I'm going to see if MallRat, the maker of Expanded Armory, can aid this in any way.

https://www.dropbox.com/s/8w91zxqsaa03hmb/balkonstextures.zip?dl=0

**Comment by Sunconure11** [comment]
However, as these are designed around the old textures, you may tweak them to your liking.

**Comment by Sunconure11** [comment]
I plan on making silver and tin items next.

**Comment by TheOnlySilverClaw** [comment]
You should really NOT use Balkon's textures if that's what you're doing now.
Otherwise, nice idea.

**Comment by ThexXTURBOXx** [comment]
It is what he does right now ;) I remember those textures

**Comment by ThexXTURBOXx** [comment]
BTW why should we add support for other materials (there are only a few mods in 1.8 using those, even Thermal Expansion and IndustrialCraft don't exist for 1.8)? The ones which are already there (Wood, Stone, Gold, Iron, Diamond) are enough

**Comment by ThexXTURBOXx** [comment]
I am not sure if so much more will come, as TeamCoFH said, that their mods will be only 1.9 next... And some others said that, too :(

**Comment by Sunconure11** [comment]
There are already a few mods on 1.8 that add such materials. Plus, it'd help make weaponry less inconsistent, if players are using mods that add tools for such materials.

**Comment by Sunconure11** [comment]
Any future textures I make will likely be designed around the Balkon's Weapons set of textures until all of the weapons from that mod are ported over, and have new textures.

**Comment by ThexXTURBOXx** [comment]
TheOnlySilverClaw already hired texturers for our own textures. It'd be very good, wehn you design your textures like the ones that are already made.

**Comment by Sunconure11** [comment]
Alright, I'll wait until all of the weaponry has been created, then I'll do new textures.

**Comment by TheOnlySilverClaw** [comment]
I think the battleaxe and the boomerang are already safe to do and will most likely not change from now on.

**Comment by Sunconure11** [comment]
I'll see about new battleaxe and boomerang textures within the next few days. I have not been sleeping well.

**Comment by Sunconure11** [comment]
While I wait for my sleep schedule to fix itself, I have a question. Is it possible to code a weapon that requires both hands to use?

**Comment by TheOnlySilverClaw** [comment]
I hope it's possible to make the entity animations do that properly, since I've been thinking about that myself.
Since Minecraft does not use left hand before 1.9, there should be minimal complications gameplay-wise.
Short answer: Maybe.

**Comment by ThexXTURBOXx** [comment]
It should be. I know the "Bioshock Mod" using the other hands for firing plasmids :D

**Comment by Sunconure11** [comment]
Alright good, because I think one weapon this mod could use is the Zweihander, a giant, germanic lomgsword.

**Comment by Sunconure11** [comment]
I'm working on a crude spreadsheet for weapon ideas. In the mean time, I'm making copper boomerangs and battleaxes. Since I doubt MallRat will get involved, I will make those textures instead. Despite my sleep schedule being fucked up, I think I should just knock this out of the way.

**Comment by Sunconure11** [comment]
https://docs.google.com/spreadsheets/d/1Tp0p0TXWaR0-l9x9-KPdCb-kJDgelJKXZD5nAzbrM_A/edit#gid=0

**Comment by Sunconure11** [comment]
Also: https://www.dropbox.com/s/eb4zi2xnauqahjd/texturesnew.zip?dl=0

Here are the textures for copper boomerangs and battleaxes.

**Comment by ThexXTURBOXx** [comment]
Looks nice, dude! When we include the textures and weapons by you in our mod, do you want to be shown in the credits or not (some people don't)... If yes: Should the name be "Sunconure11" or an other?

**Comment by Sunconure11** [comment]
If you wish. I will likely contribute other textures in the future, but, my sleep schedule is so fucked up that any textures after these in the few days will be simple ones, such as say, silver boomerangs. I don't have enough energy to make entirely new weapon textures.

**Comment by TheOnlySilverClaw** [comment]
Wait, wait, wait.
I assumed they would be for some addon/brigde-plugin-thing for material mods.
Or how do you plan to integrate them?

**Comment by Sunconure11** [comment]
I would say the items can be implemented via this mod itself, it it picks up copper or something, it will allow for the crafting of copper items. An example of this in an existing mod would be the usage of copper in Thaumcraft 4. If a mod using copper is installed, you can use copper to make wand caps.

**Comment by ThexXTURBOXx** [comment]
Yeah, I was implementing them right now, but then my Fork got updated automatically and I needed to discard my changes :(

**Comment by Sunconure11** [comment]
Expect silver items in a bit, plus a copper saber.

**Comment by Sunconure11** [comment]
I'll hold off silver until tomorrow, I need to make copper textures for the saber, musket, and resend my knife.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/fl5lef5wscnjjmc/armorycontinued.zip?dl=0

New textures!

**Comment by ThexXTURBOXx** [comment]
Added them ^^

**Comment by Sunconure11** [comment]
Sorry, I was unable to make silver textures today. I'll try and get them done whenever possible.

**Comment by ThexXTURBOXx** [comment]
Take your time... We will add the Mod Integration in version 0.7 or whenever...

**Comment by Sunconure11** [comment]
Copper katanas will come within the next few days.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/fl5lef5wscnjjmc/armorycontinued.zip?dl=0

All existing copper textures, plus the katana

**Comment by ThexXTURBOXx** [comment]
Thanks, nice! Will add them, when the integration update comes out. And I have another question: Could you do some "Manasteel"-textures later then, when it comes out? I want to add some Botania-integration then, too ^^

**Comment by Sunconure11** [comment]
I can, yes.

**Comment by Sunconure11** [comment]
However, I will only do copper until the integration update begins.

**Comment by ThexXTURBOXx** [comment]
Nice, thank you!

**Comment by Sunconure11** [comment]
Is it time for me to begin doing various textures yet? I'm going to try and texture as much stuff as I can for integration while I wait for stuff to happen with GC.

Also, it appears I need to do a texture map for the boomerang model if I do any more copper stuff.

**Comment by ThexXTURBOXx** [comment]
If you want, then create new Models for those Items using the Tabula mod (Techne as a Minecraft mod, much more up to date...). You can either create a Pull Request then or send them to us, we will include them.
As for the Integration Update: I started it 3 days ago and now we support 2 mods (Thaumcraft and ProjectE). I will try to integrate as much mods as I can; if you know some cool mods, which add new Materials, then just let it know me (But only famous mods, please no mods with only 5 Downloads ;) ). The textures for the new Items are pretty easy to make. I have done those with my basic skills in Photoshop :D But if you want, then create new textures for them in better colors (I am colorblind, I don't know, if I chose the right ones...). ^^

**Comment by Sunconure11** [comment]
Alright, I'll list some stuff.

Continue what I was doing with basic materials that most mods have until I can get back onto that, I screwed up my sleep schedule badly (due to a skype convo that lasted longer than it should have) and there are also some more pressing matters I need to attend to.

Biomes O' Plenty, Project Red, Bluepower, Base Metals (for examples of generic metals), Psi (new mod by Vazkii), Twilight Forest, Erebus, Aura Cascade, Thermal Expansion (and related mods), and probably some other stuff. Note that not all of these mods are on 1.8.9, so, disable their support until they come on 1.8.9.

I suggest gathering a list of mods to support.

**Comment by ThexXTURBOXx** [comment]
Nice list ^^
But I forgot to say, that the Biomes o Plenty Dev-versions (the versions for modders) are broken :/
I already tried to include the mod, but I can't get it work... I will try it using the universal version when I have time and will tell you about the result ^^
Thermal Expansion and Project Red don't have a 1.8-version I think (TeamCofH only want to support 1.9 then as much as I know).
But there is a 1.8-version of Botania, officially ported by williewillius. This would be very cool to include (weapons can get reloaded with mana then :+1: )

**Comment by Sunconure11** [comment]
There are builds on curseforge for BoP.

**Comment by ThexXTURBOXx** [comment]
Yeah, these are those for normal players, we need the dev-versions for modders :D

**Comment by ThexXTURBOXx** [comment]
Unfortunatley Botania got discontinued today...
But I will still make an API for the mod, because in our hearts the mod will NEVER die ^^

**Comment by TheOnlySilverClaw** [comment]
Sooo... I will have my Swedish exam on Tuesday and can hopefully finish the Necromancer's Staff next week. I'm not actually sure how to make it look, though...
Maybe the staff could be made out of obsidian, the tip could be an undead mob's head... depending on how rare the staff should be.
Any suggestions?

**Comment by Sunconure11** [comment]
Sorry, I won't be able to handle textures just yet. I need to focus my priorities on Growthcraft and Totemic. I need to finish Baykok for Lfja, and finish the Shishi-Odoshi, for Icedragon.

And also, you guys seem to be handling it well at the moment.

I'll come back to actually doing major texture work once those two major burdens have been dealt with. Sleep got fucked up again due to a Skype convo that lasted WAY too long (1 am to 6:30 am), and while I have managed to get it back on track fully, I'm finding myself waking up at 5 in the morning as of late.

**Comment by ThexXTURBOXx** [comment]
Oh, that doesn't sound good :(
Well, then get well and take your time for the textures! I will do it with my beginner-method while you aren't able to do it.
When you have time, do it, if you don't, don't do it ^^
Your healthness is much more important than our textures :D 
Get well!

**Comment by ThexXTURBOXx** [comment]
Well, this would be list of all the MISSING material textures (if we want to include every mod on the list in #124 ):
- Base Metals:
  - Adamantine
  - Aquarium
  - Brass
  - Bronze
  - Coldiron
  - Copper
  - Electrum
  - Invar
  - Lead
  - Mithril
  - Nickel (also called Ferrous)
  - Silver
  - Starsteel
  - Steel
  - Tin
  - Zinc
- BoP:
  - Amethyst
  - Mud
- Psi:
  - Psi Metal
- Aura Cascade:
  - Don't know those things in there ^^
- Botania:
  - Manasteel
  - Terrasteel
  - Elementium

If you want, then you can create those things new:
- Thaumcraft:
  - Thaumium
  - Void
- ProjectE:
  - Red Matter
  - Dark Matter
- Misc:
  - New entity models, if you want/can ^^

**Comment by Sunconure11** [comment]
I can do some of that, but, I need to finish up Baykok for Totemic. I have pretty much tweaked out all of the minor things that were bothering me, but, that model is more complicated, and requires more of my time. Once I am finished, I can do some of these things.

Sleep schedule is stable for the most part but that model requires more of my time.

**Comment by ThexXTURBOXx** [comment]
Like I said: Take your time and when you feel like it, then just create some of them ^^

**Comment by ThexXTURBOXx** [comment]
I say this here, too:
There is a new repo for the integration update.
Here is the link: [Reforged Integration](https://github.com/ThexXTURBOXx/Reforged-Integration)
