### ISSUE TITLE
Release of 0.6 [Last But Not Least]

### ISSUE THREAD

**Issue by ThexXTURBOXx** [ThexXTURBOXx/Reforged#101]
Update 10.02.16: Looks like the new version of Reforged gets WAY more stable, than we thought. Be prepared for a MAJOR update with much new features ^^

Only a few things need to get done:
- [x] Boomerangs drop in water f12a557dc81ef706e68738967f3fc8161882aaa9
- [x] Forgot method in Sabre 5203212212083d39c68f36de02f008d6ef94c990
- [x] Nest of Bees warning before shooting begins 8dd4b9eb6a176b23de51b8261660437d868380a6
- [x] Nest of Bees shouldn't shoot _so_ fast 51140fecade7089f167ad91004d86f35eb7df0c2
- [x] Fix Blunderbuss shots a3933ffc6163fd75a5ee11bbdef5e636d30c0694
- [x] Fix Knives c8a221174d73dbdaf1a87c8916503f5f93c4c4c1
- [x] Fix DamageSources (Zombie Pigmen don't attack you after you attacked them) 089fe302cecbebb2fa8082dc1b4707d3daeba2cb (improved in 3308248da6cc359159c4ecd23cb46d04ff9e7f07)
- [x] Fix Entity Rotations (The yaw is fixed... The pitch will get fixed later) 3f529cff4f6987aee44555cd54c89fddf87cc332
- [x] Fix DamageSources (Mobs not running away after you attacked them) b13f49f7371c284ade2009d02e93ecb95809de76
- [x] Improve message sent by own Version Checker 6b067236da8775da5d19c420b882878de5c10dc9 (improved in 857eb2d4767cf2c7618435db7637446c74f93c66)
- [x] Fix support for Dynious's Version Checker Mod 9c38d1a2010ec7842840731a30eb1b27fb3f6246
- [x] Create own extendable EntityThrowable-class for more cleanup 3308248da6cc359159c4ecd23cb46d04ff9e7f07 (improved in 43ea9bc116e33e51df5633c00a159e3abc0b05dc and fc3eb039cede81cf48b6376fb3918fa1c29ec8df, much improvements followed in other classes)
- [x] Create own extendable Render-class for more cleanup a1e78877fc59ed4a9506fcc03dfc0861500ea853 (improved in 1ef1bc63c087387ee493c7aa3dc29f5d63fb013f)
- [x] Create own extendable Model-class for more cleanup de504d5acbbeaf37945f3e04df72e3258f4e81d4
- [x] Switch to UUIDs for saving NBTData 3362eb61ceed0b44e857a83cd2a9148359208110
- [x] Cleanup in which all superfluous imports get removed f95e12127f66ea2732c358f0393c74b6dec1843c
- [x] Last step: Fix every bug found

**Comment by ThexXTURBOXx** [comment]
@TheOnlySilverClaw Could you do the Nest of Bees?

**Comment by TheOnlySilverClaw** [comment]
Tomorrow^^

**Comment by ThexXTURBOXx** [comment]
Nice :D

**Comment by TheOnlySilverClaw** [comment]
Ooookay, so far I managed to make it even more twitchy...

**Comment by ThexXTURBOXx** [comment]
Now it's your job to complete the list ^^

**Comment by ThexXTURBOXx** [comment]
Since it's released, I close this ^^
