### ISSUE TITLE
Plans for 0.7

### ISSUE THREAD

**Issue by ThexXTURBOXx** [ThexXTURBOXx/Reforged#107]
Well, 0.6 is nearly finished... Let's plan 0.7!
The update will be called "Shooting Heads". That means it will add more weapons. There is already a list: #56 And we have a few other issues related to 0.7 ^^
But I think, there should be added more things. Here are a few of my thoughts:
- [x] The coding fail with the "Goalseeker Boomerang" should return in an enchantment e216017eaeb7fc6710f2b3f48402cca5119dcf6d
- [x] Dynamite or something similar b7121c24c91fba39be84633ac960fc5081fa40a4
- [x] Change the recipes for the darts to Balkon's ones 60bfcc1c9c636c073b967bf99be02ac179fb7cf5
- [x] A surprise for you guys ^^ (we already have reached 1000 Downloads... Let's party!) (==> The Installer)

When our mod gets more famous, _maybe_ ask BDCraft or Soartex for creating a patch for their texturepacks? (Well, I did it already XD )

**Comment by TheOnlySilverClaw** [comment]
I'm not sooo enthusiastic about blood particles.
Own Potion Effects seem to be a pain to implement.
Own mobs...I'm not sure if that should become part of Reforged itself.

The rest sounds good, though.

**Comment by ThexXTURBOXx** [comment]
With _mob_ I appearently meant Balkon's Test Dummy XD

**Comment by TheOnlySilverClaw** [comment]
In that case, I have big plans for him anyway. :D

**Comment by ThexXTURBOXx** [comment]
Fixed everythaang
