### ISSUE TITLE
Implement Enchantments

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [ThexXTURBOXx/Reforged#109]
Some might work by default, let's test...

Melee:
- [x] Unbreaking (should work by default)
- [x] Sharpness
- [x] Smite
- [x] Bane of Arthropods
- [x] Knockback
- [x] Fire Aspect
- [x] Looting (seems to be working by default? hard to test)

Ranged:
- [ ] Power
- [ ] Punch
- [ ] Flame
- [ ] Infinity

**Comment by TheOnlySilverClaw** [comment]
Good news:
All the melee enchantments are relatively easy to do.

Bads news:
It's bad design to copy paste it to work with all the weapons...

Really bad news:
Minecraft's system for deciding what can be enchanted with what is a crappy mess of code bullshit and I cannot figure out any good way to only use enchantments that make sense for a certain weapon...

**Comment by CorruptedSlime** [comment]
It won't make sense, but it might be funny.

**Comment by Unusual-Customer** [comment]
I think infinity for musket would be too imbalanced

**Comment by TheOnlySilverClaw** [comment]
Hmyep...

By now, I think about just dropping support for enchantment tables (maybe Forge will allow some way to use it properly some day...) and maybe just go with book enchantments, maybe they're easier to fine tune... but I'm not sure. That would at least allow us to not extend vanilla classes, which is really cumbersome in some cases.

**Comment by TheOnlySilverClaw** [comment]
Sooo, my suggestion is to drop enchantment support for now, to make our classes more maintainable again. And then we can either pray that Forge will give us a proper hook for enchantments some day or hack around it, as usual, maybe with a custom enchantment block.
Anyway, we can open a new issue for that after 0.9 or later.
