### ISSUE TITLE
Make the Necromancer's Staff

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [ThexXTURBOXx/Reforged#111]
No, we won't make an own Issue for every weapon, but I'm not sure how to do this particular one, so here's a chance to make decisions. ;)

So, how should the Necromancer's Staff work?
My idea is to touch (punch) an undead creature and basically replace its AI with that of a dog, so it follows you around and attacks whatever attacks you (and/or what you attack). Any other ideas?

What should the crafting recipe be? Should there be different versions?

Should it only work on zombies? Or also skeletons?

How many undead should one staff control?

Should it be safe to use or could the undead break your control?

**Comment by Squeekblach** [comment]
Well I sort of based it on the necromancer's abilities from Diablo II where you were able to revive the enemies you killed into a skeleton warrior/mage minion or summon a living clay golem from the ground (etc).
In Diablo they would work just like a dog where they would follow you around and attack any enemies in sight.
I'm not sure reviving corpses would be a good idea so having it able to sort of tame the undead would probably work best.

**Comment by CorruptedSlime** [comment]
"Should it only work on zombies? Or also skeletons?"
"Should there be different versions?"
I have an idea to make different versions for every type of undead creature. Its appearance should differ a bit, the simplest way is to change some colors. Zombie staff should be cheaper/easier to obtain   than skeleton staff, etc. Recipe should also contain a part of desired creature (example: rotten flesh for zombie staff).

This weapon must be balanced somehow (I suggest weak durability and charge mechanic [you have to click and hold mouse button on enemy for few seconds)].

**Comment by ThexXTURBOXx** [comment]
"for every type of undead creature":
Well, if we will start working on the unbelievable "Integration update", we will have to include new ones for every mob other mods add. I think, that it would be better, if we do this in groups, like 1 for undead creatures, 1 for players (I think we can make a separate one for them), 1 for animals etc.
This would keep the mod as small as possible :3

**Comment by TheOnlySilverClaw** [comment]
"Well, if we will start working on the unbelievable "Integration update", we will have to include new ones for every mob other mods add. I think, that it would be better, if we do this in groups, like 1 for undead creatures, 1 for players (I think we can make a separate one for them), 1 for animals etc."

I'm totally for not doing that. :P 
I mean, some animals are already tamable and "taming" players would be horrible.
I think it might work best if there are, like three versions and zombies are available at tier one and tier two or three enables using it on skeletons or something.
And instead of hardcoding it, we could just have a registration method to allow certain creatures for the staff. In case anyone wants his modded undead creatures to be mindbroken. ;)

**Comment by TheOnlySilverClaw** [comment]
After sending this, I came up with another idea. We could just use a point system.

For example:

Zombies cost 5 points.
Skeletons cost 15 points.
Raising a zombie from a players corpse could cost 25 points, but gives you a minion with all the armour the player dropped on death. (just a quick idea)

So, let's say the tier 1 staff gets 20 points.
That would let you control up to 4 zombies or 1 skeleton and one zombie.
Any attempt to use it for more could give some "nice" feedback from the staff. I think some seconds of wither effect would be fitting here?

**Comment by CorruptedSlime** [comment]
How about adding staff for creatures living in the Nether (zombie pigmans and wither skeletons)?

**Comment by TheOnlySilverClaw** [comment]
@CorruptedSlime: I hadn't really thought about that...put it would not be that much of an issue with the point system. I'll just have to find out how strong wither skeletons are, since I've never thought against them that much.^^

So...the basic AI is done, but I'm not sure if I should leave it at that. It's quite passive and maybe the necromancer should have to actually use the staff to call his minions and make them attack? I'll make a poll in the forum...

**Comment by TheOnlySilverClaw** [comment]
Finally had the time to make some progress on this...imagine how cool it would be with a texture. _hint, hint_

![2016-02-20_09 29 57](https://cloud.githubusercontent.com/assets/6529548/13553877/0882fc4c-e398-11e5-994f-6dc7303a54b9.png)
![2016-03-06_12 33 31](https://cloud.githubusercontent.com/assets/6529548/13553878/0897e12a-e398-11e5-9168-e520b5b81dbf.png)

**Comment by ThexXTURBOXx** [comment]
I don't think need that here anymore ^^
