### ISSUE TITLE
How to install this

### ISSUE THREAD

**Issue by Unusual-Customer** [ThexXTURBOXx/Reforged#112]
This question maybe very stupid, but  I cpmpletely don't understand how to install your mod

**Comment by ThexXTURBOXx** [comment]
Like nearly every other mod. Just install Minecraft Forge (Download here: [Minecraft 1.8](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.8.html) or [Minecraft 1.8.9](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.8.9.html)) and drop our mod in the folder %appdata%/.minecraft/mods. That's it!
But attention! You need to download our mod for the version of Forge you are using. If you have downloaded the 1.8.9-version, then download the [1.8.9-version of our mod](http://minecraft.curseforge.com/projects/reforged/files/2282073). If you downloaded the 1.8 one, then download our [1.8-version](http://minecraft.curseforge.com/projects/reforged/files/2282072).
If you have any other questions, just write back. Else close this please!
