### ISSUE TITLE
Compatibility with M&B 2

### ISSUE THREAD

**Issue by Unusual-Customer** [ThexXTURBOXx/Reforged#115]
I have just crafted a musket and ammunition for it, then I pressed RMB, musket was loading, but after  dissappearing of progress bar it's stuck in "Loadstate:Loading"

**Comment by ThexXTURBOXx** [comment]
Uuuuhm, ok this is definetly a bug.
You have to click the button as long as the loading bar is decreasing. Then it should be loaded and be stretched like a bow. We will try to fix the Loading bar!

**Comment by Unusual-Customer** [comment]
I have been pressing RMB till the progress bar dissappeared - same thing happened. In the case of this bug neither musket, nor blunderbuss are not  working

**Comment by ThexXTURBOXx** [comment]
For me both are working... Which version of Minecraft are you using?
Edit 1: Try to hold it longer than the Loading bar is disappearing

**Comment by Unusual-Customer** [comment]
I think this problem appears because I am using M&B: Battlegear 2,  in which melee weapons can't block completely

**Comment by ThexXTURBOXx** [comment]
This could be an issue (those issues we will fix in the integration update). But I am wondering, why it even blocks shooting... I will try it with M & B tomorrow, too and will see how to fix it ^^

**Comment by Unusual-Customer** [comment]
I am using 1.8 version of Minecraft

**Comment by Unusual-Customer** [comment]
Okay then

**Comment by ThexXTURBOXx** [comment]
Alright, then I will comment again next days and we will see ^^

**Comment by ThexXTURBOXx** [comment]
Alright, after 1 month I finally have time to look over it.

**Comment by ThexXTURBOXx** [comment]
I have contacted the owner of M & B... It's a bug by his mod.

**Comment by ThexXTURBOXx** [comment]
EnumAction.Block gets cancelled by M&B 2... There is a setting in its config to turn this off (Either tell every user to do this or fix it :/
