### ISSUE TITLE
Crossbow?

### ISSUE THREAD

**Issue by Unusual-Customer** [ThexXTURBOXx/Reforged#116]
Do you plan to import crossbow from Balkon's?

**Comment by ThexXTURBOXx** [comment]
We thought about it and maybe we will add it in 0.7 already.

**Comment by ThexXTURBOXx** [comment]
BUT: We won't import it. We will completely rewrite it, like every other weapon / feature in this mod

**Comment by TheOnlySilverClaw** [comment]
We already have the textures for normal and siege crossbows. They will come, we just might do some refactoring first...

**Comment by ThexXTURBOXx** [comment]
After 1 month and 5 days, I have decided to work on it now. If you have any suggestions, just write them here ^^

**Comment by ThexXTURBOXx** [comment]
Well, now it implemented correctly and works fine (see Fixes at ecddd2631fe8e55f630f784d80dce1f1bab6420e)
