### ISSUE TITLE
Different types of musket ammunition

### ISSUE THREAD

**Issue by Unusual-Customer** [ThexXTURBOXx/Reforged#117]
I have an idea of different ammo for musket that would be interesting for you, maybe:
Explosive ball - explodes on impact, dealing 2(1 heart) areal damage in the range of 3 block. If shot in the block - destroys it
Incendiary ball - sets target on fire on impact
Penetrator ball - penetrates up to 3 mobs/players, dealing less damage after each penetration 
Firework ball - should be launched vertically, same effect as firework, but launched farther

**Comment by ThexXTURBOXx** [comment]
The Firework ball reminds me of the javelin in modern warfare 3 XD

**Comment by TheOnlySilverClaw** [comment]
I think there is really no point in doing it this way.

There will be incendiary weapons (in addition to the firerod).
The peneration thing might come with the siege crossbow or some other weapon...or with the normal musket, actually...
A Chinese rocket launcher style weapon will also come.

If we would put it all into one weapon, it would be more complicated to manage what function/ammo is used and people want thousands of varieties anyway, so why pack all of it into the musket?^^

**Comment by CorruptedSlime** [comment]
I am against this idea.

**Comment by ThexXTURBOXx** [comment]
"I am against this idea.":
Against @Unusual-Customer 's one or against @TheOnlySilverClaw 's one? ^^

**Comment by CorruptedSlime** [comment]
Against @Unusual-Customer 's idea. TOSC's arguments sound reasonable. There is no point of making different types of ammo, when you are going to create weapons which can cause similar effects.

**Comment by ThexXTURBOXx** [comment]
Yeah, that's an argument... My arguments would have been, that Balkon' Weapons Mod (the precedessor) doesn't really add much gunpowder-weapons and different type of ammo would make this mod like a Bioshock-mod...

**Comment by ThexXTURBOXx** [comment]
I close this for now, because I think, that it doesn't fit in the concept of this mod...
