### ISSUE TITLE
Not all items craftable

### ISSUE THREAD

**Issue by RaptorPower** [ThexXTURBOXx/Reforged#123]
not all of the items from Balkon's Weapons mod are in this mod! please add them all, like the flail spear boomerang Warhammer etc.

**Comment by ThexXTURBOXx** [comment]
1.) Yeah we WILL add them all...
2.)
![Just -.- FACEPALM](http://www.femtopedia.de/j.jpg)
      Is reading so hard?
3.) Solved, because see 2.)

**Comment by ThexXTURBOXx** [comment]
P.S.: Before I forget: ALL items of our mod are craftable. So the title is not right. For crafting recipes use NEI or JEI. Some recipes in our Wiki are outdated

**Comment by RaptorPower** [comment]
How do I find all of the items and the recipes?? (Dont say TooManyItems mod
it doesnt work for me)

**Comment by TheOnlySilverClaw** [comment]
Well, a lot of them should be in the Wiki, not sure how up-to-date it is, though.

**Comment by ThexXTURBOXx** [comment]
Yeah, they aren't updated yet... I will update them, when everything is ready... As I said use NEI or JEI... Those are the best ones... TMI doesn't have the ability to show crafting recipes...

**Comment by RaptorPower** [comment]
Where is the wiki

**Comment by ThexXTURBOXx** [comment]
https://github.com/TheOnlySilverClaw/Reforged/wiki
But I highly recommend those (NEI is only available for 1.8, JEI for both 1.8 and 1.8.9):
NEI: [Download here](http://chickenbones.net/Pages/links.html)
JEI: [Download here](http://minecraft.curseforge.com/projects/just-enough-items-jei)

**Comment by TheOnlySilverClaw** [comment]
If you cannot be bothered to read the front page or install NEI, you should probably not play with WIP mods. I'm locking this now.

**Comment by ThexXTURBOXx** [comment]
Why didn't I come up with that idea? XD
