### ISSUE TITLE
Integration Update

### ISSUE THREAD

**Issue by ThexXTURBOXx** [ThexXTURBOXx/Reforged#124]
Well, now it's official, that the Integration update will be included in 0.7!
I (ThexXTURBOXx) have added 2 Integrations yet: Thaumcraft and ProjectE.
However, there are still some issues, which will get fixed later (Dark and Red-Matter Tools are breakable...).

But now about the future:
Here is a little list for mods, which will get integrated then:
- [x] Thaumcraft cac6ff4cbcb6c47e12e930409f256d2fcf63cc03
- [x] ProjectE 3b56f4923ef7e7a22e092f674ef677f90937dc26
- [ ] Buildcraft
- [ ] Biomes O' Plenty (has broken API for 1.8)
- [ ] Base Metals
- [ ] Psi
- [ ] Aura Cascade
- [ ] Botania 1.8.9 (by williewillius)

And last but not least, here is a little list of other things to do:
- [ ] A class for other modders to easily register their own addons in our mod (a class with methods like createBoomerang(ToolMaterial, ...) [Maybe Later]
- [x] Better API for better usage for other modders 6c57cbedaa8c63bd0e186f7cea71f5f40373b023

**Comment by Sunconure11** [comment]
Thermal Expansion and the like, when they move to 1.8, might be good integration targets too.

**Comment by ThexXTURBOXx** [comment]
The Integration update will be in a separate mod. You can view the repo [here](https://github.com/ThexXTURBOXx/Reforged-Integration)
IMPORTANT! ANY BUG RELATED TO INTEGRATION SHALL BE REPORTED THERE, NOT IN THIS REPO!

**Comment by ThexXTURBOXx** [comment]
A little update:
I will only include mods, which have working 1.8-APIs...
We will stop supporting 1.8 in near future. Then we will only support 1.8.9.
If the time has approached, we will add Integrations for 1.8.9-mods, too.

**Comment by ThexXTURBOXx** [comment]
And I close this, new Issue can be found here: [Other repo](https://github.com/ThexXTURBOXx/Reforged-Integration/issues/1)
