### ISSUE TITLE
Bugs in 1.9 / 1.10

### ISSUE THREAD

**Issue by ThexXTURBOXx** [ThexXTURBOXx/Reforged#131]
Ok, I am working on a 1.9-port...
The Source can be found [here](https://github.com/TheOnlySilverClaw/Reforged/tree/1.9-%280.6.1%29).
There are no compile errors anymore, BUT some bugs came up now.
I list them here:
- [x] Entity Renderer causing crash 17893e21fd3662fe5d0c22b3adad5b271dadbc73
- [ ] Item Rotations and Scale broken
- [ ] Entities instantly fall down when thrown
- [ ] There is a black square behind the Hotbar-Slots (ReloadOverlay-class related problem)...
- [ ] Some Helper-methods don't work right

**Comment by ThexXTURBOXx** [comment]
Work paused until a stable 1.9-Build released

**Comment by CorruptedSlime** [comment]
Are you working on a 1.9 port? really?

**Comment by ThexXTURBOXx** [comment]
Well, I was ^^
I was thinking it wouldn't be so hard to do, but I was wrong...
Now I am waiting for a stable 1.9-build (I found MUCH bugs in Forge in the current builds...)

**Comment by ThexXTURBOXx** [comment]
I close this until I released 0.7-final
