### ISSUE TITLE
Add a config option to change enchantment IDs

### ISSUE THREAD

**Issue by Sunconure11** [ThexXTURBOXx/Reforged#137]
http://pastebin.com/J79GBGQb

Using the alpha build from curse gives me this crash.

**Comment by Sunconure11** [comment]
Holy shit, user error. Closing. Didn't realize you guys added enchantments.

**Comment by Sunconure11** [comment]
Looks like you guys need to add a config option to change the enchantment ID.

Also, I'm still waiting on Growthcraft 2.5.0 to get a full release before I send out new textures.

Also, are you guys fine with 3D models for items? I have an idea for the Zweihander...

**Comment by ThexXTURBOXx** [comment]
Of course, I only have to figure out how to include them in 1.8 (I have done that in 1.6 the last time xD ). In the next release, there will be a crossbow and a option to change the enchantment-ID. Thanks for reporting ^^

**Comment by ThexXTURBOXx** [comment]
Fixed in 0a7f92c8f4b8119aac9384da38deb329c97ca412
