### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by pixe1reality** [ThexXTURBOXx/Reforged#140]
After reading the license, I was wondering what is the developer's stance on copying code for use in other mods. I'm trying to create a mod of my own, and I would like to copy certain pieces of code, and modify the derived code in my own mod.

**Comment by TheOnlySilverClaw** [comment]
If you are planning to copy larger parts of our code, please give credit in a reasonable way. Otherwise, feel free to take some inspiration. ;)

**Comment by pixe1reality** [comment]
Thanks for clearing things up! o/

**Comment by ThexXTURBOXx** [comment]
Since now:
8e4ea82776f977b5882317fd87eb3ddb80a3c97c and 71619a62251c65ebf3a2f696ddd25f6db6876165
