### ISSUE TITLE
Russian and Ukrainian translation

### ISSUE THREAD

**Issue by Pivoslave** [ThexXTURBOXx/Reforged#142]
Add the Russian and Ukrainian translate files, I'd be glad to translate the mod!

**Comment by ThexXTURBOXx** [comment]
Hi DenTheUA, I added them.
Can you manage to do this until tomorrow?
I plan to release the new version then and it would be cool to have your translation in there, too :)

**Comment by ThexXTURBOXx** [comment]
Btw.: They are here: https://github.com/TheOnlySilverClaw/Reforged/tree/master/resources/assets/reforged/lang
(the ru_RU.lang and uk_UA.lang)

**Comment by ThexXTURBOXx** [comment]
Wow, thanks for translating both now :)
The Ukrainian translation will be in the update 0.7-pre4 then.
Thanks 1000 times ^^

**Comment by Pivoslave** [comment]
If you need me,then you know where to f-i-i-i-i-i-i-i-i-i-i-ind me^_^
