### ISSUE TITLE
Crossbow Bolts not visible in 1.8.9-version

### ISSUE THREAD

**Issue by ThexXTURBOXx** [ThexXTURBOXx/Reforged#147]
Why??? o_O

**Comment by TheOnlySilverClaw** [comment]
Try switching out the renderer class. If it's visible with another renderer, it's probably an OpenGL issue. Otherwise maybe the coordinates are wrong for some reason?

**Comment by ThexXTURBOXx** [comment]
Ah, only forgot the inferred argument.
Updated the guide: 83eb323fac2a1d0973979773c2cf0529612af7f1
