### ISSUE TITLE
Battleaxe?

### ISSUE THREAD

**Issue by peeviddy** [ThexXTURBOXx/Reforged#149]
now that 1.9 counts axes as proper weapons, why create a new battleaxe item?

**Comment by TheOnlySilverClaw** [comment]
That's actually one of the many issues why I did not want to update to 1.9.
I guess it would make sense to remove the Battleaxe, but porting Reforged to 1.9 and upwards would require a bunch of other changes, too.
Well, Turbo will have the last word in this. ;)

**Comment by ThexXTURBOXx** [comment]
I already tried to update the mod once for 1.9 and there were about 120 compile errors and even after fixing them all, I couldn't manage to e.g. throw a Boomerang without crashing Minecraft or shoot with a Musket. I can try updating again later on _(eventually)_, but I don't wanna promise anything!

**Comment by peeviddy** [comment]
I'm just getting into modding myself, so maybe I'll give this a try :)

**Comment by ThexXTURBOXx** [comment]
If you want, just go ahead and try it ^^
Should I create a new branch in this repo for you?

**Comment by peeviddy** [comment]
ooh not just yet, let me learn more about mod structure and stuff cause I'm literally brand new to this

**Comment by ThexXTURBOXx** [comment]
No problem, just ask me, when you want to start.

**Comment by TheRandomLabs** [comment]
Are you going to update this mod to 1.10.2/1.11.2? If not, I would like to give it a rewrite.

**Comment by ThexXTURBOXx** [comment]
I am planning a rewrite, too, but after my A-Levels (that means after the 3rd June).

**Comment by ThexXTURBOXx** [comment]
Now, that it's released, I close this issue for now, as we don't need this anymore (I think) :)
