### ISSUE TITLE
Question: Did you guys ever experience a crash when extending ItemAxe?

### ISSUE THREAD

**Issue by peeviddy** [ThexXTURBOXx/Reforged#151]

**Comment by ThexXTURBOXx** [comment]
Hmmm... You need this for your mod, right? ^^
Do you have any crash-reports? If yes, they could help.
We didn't experience such crashes

**Comment by peeviddy** [comment]
sorry for replying so late, it's cause I figured out my problem

**Comment by ThexXTURBOXx** [comment]
Ok, good to hear :)
