### ISSUE TITLE
Boomerang does not come back.

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [ThexXTURBOXx/Reforged#21]
That's pretty much the point of boomerangs! :P

**Comment by ThexXTURBOXx** [comment]
And I get those difficult issues everytime ^^

**Comment by TheOnlySilverClaw** [comment]
Well, you wanted to dive head first into making a boomerang. Deal with it. :P

**Comment by ThexXTURBOXx** [comment]
Ok :D

**Comment by ThexXTURBOXx** [comment]
Alpha added (Worked, but needs some tweaks. And needs bugfixes ==> getThrower() after worldsave broken!)

**Comment by ThexXTURBOXx** [comment]
Fixed Alpha, should work now. If it doesn't, just reply to this

**Comment by ThexXTURBOXx** [comment]
Only thing, that doesn't work right now: DON'T SAVE WHILE BOOMERANG STILL FLIES...
WILL BREAK YOUR WORLD!

**Comment by TheOnlySilverClaw** [comment]
NEEDS MORE CAPS!

**Comment by ThexXTURBOXx** [comment]
Maybe needs some tweaks, but done :D
