### ISSUE TITLE
Sunconure's sleep schedule is broken.

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [ThexXTURBOXx/Reforged#22]
I do not want that. I know what a broken sleep schedule does to people and it's not a good thing. :(

Get well and no rush with the textures!

**Comment by Sunconure11** [comment]
Its recovering, and I might be able to do copper daggers today. Keep in mind this happened partially because of working too hard with Growthcraft's Milk Module.

**Comment by ThexXTURBOXx** [comment]
Ah, don't hurry! Just take the time you need. We'll give you enough time :D If your sleep schedule is still broken ==> Then fix this before you create our textures (healthiness before textures!).

**Comment by Sunconure11** [comment]
![copper_knife](https://cloud.githubusercontent.com/assets/5614902/12427220/0a618f80-beac-11e5-9658-0fc19100724d.png)

**Comment by Sunconure11** [comment]
I also tweaked some of my armor and weapon suggestions a bit. Go and check them out, to see if they fit better.

**Comment by Sunconure11** [comment]
Intimidation stuff actually does stuff to mobs now too.

**Comment by ThexXTURBOXx** [comment]
Yeah, I see :D I hope, that your sleep schedule is better now ^^ Thank you!

**Comment by TheOnlySilverClaw** [comment]
There's really no reason to rush, since it usually takes longer to code a new item than to draw or recolor it. ;)

**Comment by Sunconure11** [comment]
Sleep schedule has recovered. Expect silver textures this weekend.

**Comment by TheOnlySilverClaw** [comment]
Good to hear. :D
