### ISSUE TITLE
Add some weapons

### ISSUE THREAD

**Issue by ThexXTURBOXx** [ThexXTURBOXx/Reforged#56]
https://docs.google.com/spreadsheets/d/1Tp0p0TXWaR0-l9x9-KPdCb-kJDgelJKXZD5nAzbrM_A/edit#gid=0
But not all I think (because of OP-ness, excessive accumulation etc.)
List (ticked means, that it could still need tweaks, but it has been added including its features):
- [x] Keris as Ceremonial Dagger
- [x] Necromancer's Staff (In Reforged CaG-Addon)
- [x] Caltrops
- [x] Pike
- [x] Mace
- [x] Dirk (might take that feature to the knife we have now)

**Comment by TheOnlySilverClaw** [comment]
What I would take with over 90% confidence so far:

Keris as Ceremonial Dagger
Pike
Greek Fire or at least Pitch (definitely after 1.0)
Caltrops
Mace
Necromancer's Staff (not necessarily for 1.0)
Dirk  (might take that feature to the knife we have now)
Ballista (siege weapon update)
Battering Ram (siege weapon update)
Hwacha (siege weapon update)

**Comment by Sunconure11** [comment]
If the Keris is added, can you add support for enchantments such as repair from Thaumcraft for it? IRL, they are believed to be magical by some.

https://en.wikipedia.org/wiki/Kris#Cultural_beliefs

**Comment by ThexXTURBOXx** [comment]
I think we will do an special update (maybe 0.9 or so...), which will be called the "integration update" or something like that :D

**Comment by TheOnlySilverClaw** [comment]
Will close this for now, since the spreadsheet link is in the wiki and other places, and ideas that will be adapted will be announced from time to time. Further discussion can go to the Minecraft forum. Or open new issues for very specific weapons.

**Comment by ThexXTURBOXx** [comment]
With the list we don't need to open up nearly hundreds of issues...

**Comment by TheOnlySilverClaw** [comment]
I will still use issues for more complicated stuff like the Necromancer's Staff or Pitch :P

**Comment by ThexXTURBOXx** [comment]
Got all of 'em
