### ISSUE TITLE
Mod should be built against 1.8.9

### ISSUE THREAD

**Issue by Sunconure11** [ThexXTURBOXx/Reforged#68]
1.8.9 is shaping up to be one of the more relevant builds of 1.8, with most mods for 1.8 being built against it. Shouldn't we move to it?

**Comment by ThexXTURBOXx** [comment]
MOVE: no :D 
RELEASE: yeah, but the final 0.6 ^^

**Comment by ThexXTURBOXx** [comment]
Ok, for those who really want 1.8.8 and 1.8.9 I will release the 0.5.8-alpha-hotfix1 today... But I think not every build will be released in those versions

**Comment by ThexXTURBOXx** [comment]
I won't do a 1.8.8... Tested it: Too instable - Doesn't even support all methods of Forge

**Comment by ThexXTURBOXx** [comment]
Released pretty buggy 1.8.9-version
