### ISSUE TITLE
Create the Javelin

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [ThexXTURBOXx/Reforged#7]
Make a Javelin that meets the description in the Wiki.

**Comment by ThexXTURBOXx** [comment]
Javelin now has those features:
- Entity, which does damage
- Spear-item
- The Javelin, when fired, gets rotated, so it looks in the same direction like the player (only for making it look more realistic)
- On-Hit: Item drop...
- Special effects (Look in the Wiki)

To-Dos:
- _Maybe_ some more variants (in different materials)

**Comment by ThexXTURBOXx** [comment]
Javelin now has those features:

 + Entity, which does damage
 + Spear-item
 + The Javelin, when fired, gets rotated, so it looks in the same direction like the player (only for making it look more realistic)

To-Dos:

 + New Model for nicer look
 + *Maybe* some more variants (in different materials)
 + Special effects
