### ISSUE TITLE
CurseForge Logo

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [ThexXTURBOXx/Reforged#74]
We need a logo image with 1:1 ration and at least 400px in size for the CurseForge project page.

**Comment by Squeekblach** [comment]
Err, I was assigned to help with this. I'm not sure where to start. What do you want it to look like?

**Comment by ThexXTURBOXx** [comment]
Hmmm... I think, because our mod adds pretty much medieval things: It should look "medieval". I don't know how to describe that better...

**Comment by Squeekblach** [comment]
![reforged_curselogo](https://cloud.githubusercontent.com/assets/16748858/12797734/67b51c68-ca93-11e5-9df4-2c032f20670a.png)
Would that work?

**Comment by ThexXTURBOXx** [comment]
Added it for now. I like it! I don't know what Silvercatcher thinks about it.
He can gripe if he needs to :P 
XD

**Comment by TheOnlySilverClaw** [comment]
I'm not griping :p 

But maybe use four weapons: one from each 'age' and a 'magical' one, where the holy cross would be the only option so far. So, musket and javelin would make good choices, but maybe the battleaxe to present medieval?
Or maybe keep them crossed over, but use the javelin, iron battleaxe and musket in that order, So, javelin would point to upper left corner, battleaxe would point straight up and musket upper right?

**Comment by Squeekblach** [comment]
![curselogo](https://cloud.githubusercontent.com/assets/16748858/12822257/3678c9ae-cb35-11e5-8af4-d86c8661cb84.png)
If the weapons are crossed it looks weird...

**Comment by TheOnlySilverClaw** [comment]
Hmm...what a shame...but I still really want to have all ages represented. :/

Anyway, if we go with this layout, the grey background makes it hard to see the blades.

Maybe change it to...something red...ish? Maybe that goes well with weapons?^^

**Comment by ThexXTURBOXx** [comment]
I think we can close this... I think the logo looks cool
