### ISSUE TITLE
Language File

### ISSUE THREAD

**Issue by CorruptedSlime** [ThexXTURBOXx/Reforged#79]
Hello!
I would be pleased if you look at file below. I hope there won't be any problems with letters.
http://www102.zippyshare.com/v/CxuaBcTB/file.html

**Comment by TheOnlySilverClaw** [comment]
I put in into the language folder for now, we can test it in the next release.
And maybe you can update it from time to time?

**Comment by ThexXTURBOXx** [comment]
Thanks for helping us! ^^ I let it reopened it, so you can still comment on this

**Comment by CorruptedSlime** [comment]
I will update it as soon as you add more cool stuff. I'm not sure but it seems to me that I can edit this file directly on this website.

**Comment by TheOnlySilverClaw** [comment]
Maybe you can, but you have to make a pull request? But yes, that would be more practical than keeping this issue open and checking all the time.^^

**Comment by ThexXTURBOXx** [comment]
I updated the language file. Could you pls look after the musket-translations? I don't know if I translated the "xxx Musket with Bayonet" right.
