### ISSUE TITLE
Tweak effect amplifiers for blowgun darts.

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [ThexXTURBOXx/Reforged#86]
I think the dart effects are currently too weak to do anything.
We have to find out what amplifier values make sense.

**Comment by ThexXTURBOXx** [comment]
and we need to check why the effects are not applied to other entities (like zombies etc.). The only entity which can be affected is the player :/

**Comment by TheOnlySilverClaw** [comment]
I don't think so. Poison, for example, cannot be applied to undead or spiders. Hunger should not work for mobs anyway. But I think the rest would be working, if the amplifier values would be higher. I used the slow effect to stun a zombie once, so I know that definitely works.

**Comment by ThexXTURBOXx** [comment]
Ah yeah. Forgot about the poison + undead-feature... Sorry ^^

**Comment by ThexXTURBOXx** [comment]
#95 Now it's OK, I think
