### ISSUE TITLE
Sound Requests

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [ThexXTURBOXx/Reforged#87]
I guess it's unlikely, but it cannot hurt to ask. ;)

We would currently need:
- [ ] Something like a clerical choir for the Holy Cross [Reforged CaG]
- [x] Some explosions, especially for musket, blunderbuss and mortar.
- [x] Break and Hit sounds for Boomerangs.

**Comment by ThexXTURBOXx** [comment]
Important, too. I found some Creative Commons Sounds, that I use now.

**Comment by ThexXTURBOXx** [comment]
As CaG is discontinued for now, I close this issue and reopen, wehen we work on it, again
